Controllers/DojoActivityController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using DojoActivity.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace DojoActivity.Controllers
{
    public class DojoActivityController : Controller
    {
        private UserContext dbContext;
        public DojoActivityController(UserContext context)
        {
            dbContext = context;
        }

// GET: /Home/
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            List<User> allUsers = dbContext.UsersTable.ToList();
            ViewBag.AllUsers = allUsers;
            return View();   // this is same as return View("Index")
        }
        
//Registration process
        [HttpPost]
        [Route("/registration")]
        public IActionResult RegistrationProcess(User user)
        {
            List<User> allUsers=dbContext.UsersTable.ToList();
            ViewBag.AllUsers = allUsers;

            if (ModelState.IsValid)
            {
                if(dbContext.UsersTable.Any(u => u.Email == user.Email))
                {
                    ModelState.AddModelError("Email", "Email already in use. use other email!!");
                    return View("Index");
                }

                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                user.Password = Hasher.HashPassword(user, user.Password);

                dbContext.Add(user);
                dbContext.SaveChanges();

                //setting user's firstname in session
                HttpContext.Session.SetString("firstName", user.FirstName);
                HttpContext.Session.SetString("lastName", user.LastName);
                HttpContext.Session.SetInt32("UserId", user.UserId);

                

                return RedirectToAction("Dashboard");
            }
            return View("Index");
        }

//Login process
        [HttpPost]
        [Route("/login")]
        public IActionResult LoginProcess(LoginUser userSubmission)
        {
            List<User> allUsers = dbContext.UsersTable.ToList();
            ViewBag.AllUsers = allUsers;

            if(ModelState.IsValid)
            {
                var userInDb = dbContext.UsersTable.SingleOrDefault(u => u.Email == userSubmission.LoginEmail);
                if(userInDb == null)
                {
                    ModelState.AddModelError("LoginEmail", "Invalid Email!! Maybe you need to register first!!");
                    return View("Index");
                }
                var hasher = new PasswordHasher<LoginUser>();
                var result = hasher.VerifyHashedPassword(userSubmission, userInDb.Password, userSubmission.LoginPassword);

                if(result == 0)
                {
                    ModelState.AddModelError("LoginPassword", "Invalid password. it did not match with database password!!");
                    return View("Index");
                }
                HttpContext.Session.SetString("firstName", userInDb.FirstName);
                HttpContext.Session.SetString("lastName", userInDb.LastName);
                HttpContext.Session.SetInt32("UserId", userInDb.UserId);


                return RedirectToAction("Dashboard");
            }
            return View("Index");
        }

//delete process
        [HttpGet]
        [Route("/delete/{deleteId}")]
        public IActionResult DeleteUser(int deleteId)
        {
            User deleteOne = dbContext.UsersTable.SingleOrDefault(r => r.UserId == deleteId);
            dbContext.UsersTable.Remove(deleteOne);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

//logout process
        [HttpGet]
        [Route("/logout")]
        public IActionResult Logout()
        {
            
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }

    

//Registration/Login success process and routes to Home = Dashboard
        [HttpGet("/home")]
        public IActionResult Dashboard()
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.firstname = HttpContext.Session.GetString("firstName");
            ViewBag.lastname = HttpContext.Session.GetString("lastName");

            int? UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.userId = HttpContext.Session.GetInt32("UserId");

            List<Activity> activitywithparticipant = dbContext.ActivityTable.Include(w => w.participant).Include(w => w.Creator).ToList();

            return View(activitywithparticipant);
        }

//render new Activity page
        [HttpGet]
        [Route("/new")]
        public IActionResult NewMethod()
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.firstname = HttpContext.Session.GetString("firstName");
            ViewBag.lastname = HttpContext.Session.GetString("lastName");

            int? UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.userid = HttpContext.Session.GetInt32("UserId");

            return View("NewPage");
        }

//create method
        [HttpPost]
        [Route("/createRoute")]
        public IActionResult CreateMethod(Activity schedule)
        {

            ViewBag.firstname = HttpContext.Session.GetString("firstName");
            ViewBag.lastname = HttpContext.Session.GetString("lastName");

            
            if(ModelState.IsValid)
            {
                if(schedule.Date <= DateTime.Today)
                {
                    ModelState.AddModelError("Date", "Date must be set to the future date!!");
                    return View("NewPage");
                }

                if(schedule.Time <= DateTime.Today)
                {
                    ModelState.AddModelError("Time", "Time must be set to the future Time!!");
                    return View("NewPage");
                }
                schedule.UserId = (int)HttpContext.Session.GetInt32("UserId");

                dbContext.Add(schedule);
                dbContext.SaveChanges();
                
                System.Console.WriteLine("################################################");
                System.Console.WriteLine("################################################");
                System.Console.WriteLine("################################################");
                System.Console.WriteLine("################################################");
                System.Console.WriteLine("################################################");
                System.Console.WriteLine("################################################");

                return RedirectToAction("Dashboard");
            }
            return View("NewPage");
        }

//show One method
        [HttpGet]
        [Route("/show/{showId}")]
        public IActionResult ShowMethod(int showId)
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.firstname = HttpContext.Session.GetString("firstName");
            ViewBag.lastname = HttpContext.Session.GetString("lastName");

            int? UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.userid = HttpContext.Session.GetInt32("UserId");

            Activity showOne = dbContext.ActivityTable.Include(w => w.participant).ThenInclude(w => w.User).SingleOrDefault(h =>h.ActivityId == showId);
            ViewBag.ShowOne = showOne;

            return View();
        }

//delete one
        [HttpGet]
        [Route("/deleteOne/{deleteOneId}")]
        public IActionResult DeleteOne(int deleteOneId)
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index");
            }
            Activity Current = dbContext.ActivityTable.SingleOrDefault( d => d.ActivityId == deleteOneId);
            dbContext.ActivityTable.Remove(Current);
            dbContext.SaveChanges();
            return RedirectToAction("Dashboard");
        }

//rsvp method
    [HttpGet]
        [Route("//rsvp/{wId}")]
        public IActionResult RSVP(int wId)
        {
            
            //check user in session
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index");
            }
            //get the session id 
            User currentUser = dbContext.UsersTable.SingleOrDefault( c => c.UserId == HttpContext.Session.GetInt32("UserId"));

            Activity currAct = dbContext.ActivityTable.Include( w => w.participant).ThenInclude(w => w.User).SingleOrDefault(r => r.ActivityId == wId);
            Participant thisparticipant = dbContext.ParticipantTable.Where(j => j.ActivityId == wId && j.UserId == currentUser.UserId).SingleOrDefault();
            
            if(thisparticipant != null)
            {
                currentUser.participant.Remove(thisparticipant);
            }
            else{
                Participant newParticipant = new Participant
                {
                    UserId = currentUser.UserId,
                    ActivityId = currAct.ActivityId,
                };
                currAct.participant.Add(newParticipant);
            }
            dbContext.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        
    }
}

Views/DojoActivity/Dashboard.cshtml
@using DojoActivity.Models
@model List<Activity>

        <style>
            table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
            }

            td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
            }

            tr:nth-child(even) {
            background-color: #dddddd;
            }
        </style>

        <h2>Dojo Activity Center</h2> <span style="color:red">Welcome @ViewBag.firstname @ViewBag.lastname !</span><br><br>
        <a href="/logout">Log off</a>
        <hr>
        <a href="/new">Add New Activity!</a>
        <hr>

        <table>
            <tr>
                <th>Activity</th>
                <th>Date and Time</th>
                <th>Durantion</th>
                <th>Event Coordinator</th>
                <th>Number of Participants</th>
                <th>Actions</th>
            </tr>
            @{
                foreach (var w in @Model)
                {
                <tr>
                    <td><a href="/show/@w.ActivityId">@w.Title</a></td>
                    <td>@w.Date.ToString("MM/dd/yyyy @")  @w.Time.ToShortTimeString()</td>
                    <td>@w.Duration @w.DurationForm</td>
                    <td>@w.Creator.FirstName @w.Creator.LastName </td>
                    <td>@w.participant.Count</td>

                    <td> 
                        @{
                            var count =0;
                            foreach (var g in @w.participant)
                            {
                                if(@ViewBag.UserId == g.UserId)
                                {
                                    count++;
                                }
                            }
                        
                            if(count ==0)
                            {
                                <a class="btn btn-success" href="/rsvp/@w.ActivityId">Join</a>
                            }
                            else
                            {
                                <a class="btn btn-danger" href="/rsvp/@w.ActivityId">Leave</a>
                            }
                        }
                        @if(@ViewBag.UserId == @w.UserId)
                        { 
                        <a href="/deleteOne/@w.ActivityId"> | Delete</a>
                        }
                    
                    </td>
                    </tr>
                }
            }
                
            </tr>
        </table>

Views/DojoActivity/Index.cshtml

    <div style="float:left">
        <partial  name="LoginForm"></partial>
    </div>

    <div style="float:right">
        <partial  name="RegistrationForm"></partial>
    </div>

    <center>
        <h3>Website created by Rabin Gora</h3>
        @{
            foreach (var i in @ViewBag.AllUsers)
            {
                <p>@i.FirstName | @i.Email | <a href="/delete/@i.UserId"> Delete</a></p>
            }
        }
    </center>

Views/DojoActivity/LoginForm.cshtml
@using DojoActivity.Models
@model LoginUser

<div>
    <form asp-action="LoginProcess" asp-controller="DojoActivity" method="post">
        <h3>Login</h3>

        <span asp-validation-for="LoginEmail" style="color:red"></span><br>
        <p>Email:<br><input type="text" asp-for="LoginEmail"></p>

        <span asp-validation-for="LoginPassword" style="color:red"></span><br>
        <p>password:<br><input type="password" asp-for="LoginPassword"></p>

        <button type="submit">Login</button>
    </form>
</div>

Views/DojoActivity/NewPage.cshtml
@using DojoActivity.Models
@model Activity

<h2>Dojo Activity Center</h2> <span style="color:red">Welcome @ViewBag.firstname @ViewBag.lastname! </span><br><br>
<a href="/home">Home</a> | <a href="/logout">Log off</a>
<hr>
<div>
    <form asp-action="CreateMethod" asp-controller="DojoActivity" method="post">

        <span asp-validation-for="Title" style="color:red"></span><br>
        <P>Title: <input type="text"asp-for="Title" ></P>

        <span asp-validation-for="Date" style="color:red"></span><br>
        <P>Date: <input type="Date" asp-for="Date"></P>

        <span asp-validation-for="Time" style="color:red"></span><br>
        <P>Time: <input type="Time" asp-for="Time"></P>

        <span asp-validation-for="Duration" style="color:red"></span><br>
        <P>
            Duration: <input type="number" asp-for="Duration"> 
            
            <select asp-for="DurationForm">
                <option value="Days">Days</option>
                <option value="Hours">Hours</option>
                <option value="Minutes">Minutes</option>
            </select>
        </P>

        <span asp-validation-for="Description" style="color:red"></span><br>
        <P>Description: <input type="text" asp-for="Description"></P>

        <button type="submit">Create Activity</button>
    </form>
</div>

Views/DojoActivity/RegistrationForm.cshtml
@using DojoActivity.Models
@model User
<div>
    <form asp-action="RegistrationProcess" asp-controller="DojoActivity" method="post">
        <h3>Register</h3>

        <span asp-validation-for="FirstName" style="color:red"></span>
        <p>First Name:<br><input type="text" asp-for="FirstName"></p>

        <span asp-validation-for="LastName" style="color:red"></span>
        <p>Last Name:<br><input type="text" asp-for="LastName"></p>

        <span asp-validation-for="Email" style="color:red"></span>
        <p>Email:<br><input type="text" asp-for="Email"></p>

        <span asp-validation-for="Password" style="color:red"></span>
        <p>Password:<br><input type="password" asp-for="Password"></p>

        <span asp-validation-for="ConfirmPassword" style="color:red"></span>
        <p>Password:<br><input type="password" asp-for="ConfirmPassword"></p>

        <button type="submit">Register</button>
    </form>
</div>

Views/DojoActivity/ShowMethod.cshtml
@using DojoActivity.Models;
@model Activity;

<h2>Dojo Activity Center</h2>
<hr>
<a href="/home">Home</a> | <a href="/logout">Log off</a>
<hr>
<h2>@ViewBag.ShowOne.Title</h2>

<h3 style="color:grey"> Event Coordinator: SomeOne</h3>

<h3 style="color:grey"> Date: @ViewBag.ShowOne.Date.ToString("MM/dd/yyyy")</h3>
<h3 style="color:grey"> Date: @ViewBag.ShowOne.Time.ToShortTimeString()</h3>
<h3 style="color:grey"> Description: @ViewBag.ShowOne.Description</h3>

<h4 style="color:gray">Participants:</h4>
@{ 
    <ul style="color:gray">
        @foreach (var h in @ViewBag.ShowOne.participant)
        {
            <li>@h.User.FirstName @h.User.LastName</li>
        }
    </ul>
}